### PR TITLE
Update containers' latest tag and add the docker.io/iterativeai registry

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
### From https://github.com/iterative/cml/issues/383#issuecomment-870834591

- [x] Make `latest` point to `0-dvc2-base1-gpu` or whatever the latest tag is
- [x] Push active tags to `@iterativeai/cml` and soft-deprecate `@dvcorg/cml`
- [x] Check credentials — ideally one bot user with push access to both organizations [#infrastructure➔1625237297087600](https://iterativeai.slack.com/archives/C01R00PPQ1L/p1625237297087600)

### CODE REVIEW

**Comment by 0x2b3bfa0** [comment]
⚠️ Untested, whiteboard-quality code. Please sanity-check thrice before approving.

**Review by casperdcl — APPROVED** [review]

**Review by casperdcl — APPROVED** [review]
bugs found; bugs fixed.

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 is this ready?

**Comment by 0x2b3bfa0** [comment]
@casperdcl fixed and approved it, so I guess that is "ready enough"

**Pull request merged**
