### PR TITLE
Revert GitLab Runner version pin

### LINKED ISSUE #1335: Revert GitLab Runner version pin
See #1333, #1329, [gitlab-org/gitlab-runner#29592](https://gitlab.com/gitlab-org/gitlab-runner/-/issues/29592) and [gitlab-org/gitlab-runner!3881](https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/3881) for context.

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
Reverts #1333 and closes #1335; to be merged as soon as [!3881](https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/3881) is released.

### CODE REVIEW

**Comment by dacbd** [comment]
@0x2b3bfa0 convert to draft while it's blocked?

**Comment by tasdomas** [comment]
15.8.2 is already out with the fix merged, should we land this?

**Comment by 0x2b3bfa0** [comment]
@tasdomas, it looks like it hasn't been released yet (?) 🤔 

```console
$ curl --location https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64 --output /bin/gitlab-runner
...
$ gitlab-runner --version
Version:      15.8.2
Git revision: 4d1ca121
Git branch:   15-8-stable
GO version:   go1.18.9
Built:        2023-02-09T17:23:17+0000
OS/Arch:      linux/amd64
$ gitlab-runner run-single --executor=docker --url=https://gitlab.com --token=$GITLAB_RUNNER_REGISTRATION_TOKEN
...
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
...
```

**Comment by 0x2b3bfa0** [comment]
They haven't backported the patch to the `15-8-stable` branch yet.

**Comment by 0x2b3bfa0** [comment]
@iterative/cml, ready to merge after GitLab back ported the fix to 15.8 stable.

**Review by dacbd — APPROVED** [review]

**Pull request merged**
