### PR TITLE
docs: `repo_token` => `REPO_TOKEN`

### PR DESCRIPTION
**Pull request by casperdcl**
Follow-up to #489﻿

### CODE REVIEW

**Comment by 0x2b3bfa0** [comment]
Please note that we currently have our documentation spread ofver a few places; you may also want to update https://cml.dev ([source](https://github.com/iterative/cml-website)) and https://dvc.org/doc/cml ([source](https://github.com/iterative/dvc.org/tree/master/content/docs/cml)).

clippy

**Comment by casperdcl** [comment]
Wait what.

https://dvc.org/doc/cml is just a mirror of this repo's [README](https://github.com/iterative/cml/). Much duplication such inefficient. @jorgeorpinel @shcheklein any better suggestions? I'd really rather dvc.org/doc/cml was a one page blurb containing links to this repo and cml.dev

**Comment by 0x2b3bfa0** [comment]
I'm inclined to think that it would be better to keep documentation in a single place (preferably [cml.dev](https://cml.dev)) and point to it from both [dvc.org/doc/cml](https://dvc.org/doc/cml) and the `README.md` file.

**Review by 0x2b3bfa0 — APPROVED** [review]

**Review by jorgeorpinel — APPROVED** [review]
> https://dvc.org/doc/cml is just a mirror of this repo's README. Much duplication such inefficient. @jorgeorpinel @shcheklein any better suggestions? I'd really rather prefer dvc.org/doc/cml to be a one page blurb containing links to this repo & cml.dev

Yeah I think the README existed first and was the main documentation. At some point we needed to publish CML docs somewhere formal for some reason so it was copied over. Definitely should not have the same content. The Q is what's the vocation of each one? README vs CML docs (home page), that is.

Same Q applies for DVC BTW... @casperdcl do you want to make an issue about the product READMEs in the docs repo?

**Comment by jorgeorpinel** [comment]
\* Definitely should **not**

**Comment by casperdcl** [comment]
Sure @jorgeorpinel I just opened https://github.com/iterative/dvc.org/issues/2443 which is going to be fun :)

**Pull request merged**
