### PR TITLE
Cloud metadata

### LINKED ISSUE #430: Tagging of instances on AWS
Is it possible to apply tags to instances created on AWS? I've tried the `--label` option, but I can't see where this is propagated into instances in AWS.

### PR DESCRIPTION
**Pull request by DanielBarnes**
Closes #430 
Supercedes or Blocked by: #747
Requires upstream: https://github.com/iterative/terraform-provider-iterative/issues/185

Manual testing:
```bash
./bin/cml.js runner \
    --single \
    --log=debug \
    --idle-timeout=1800 \
    --token=xxx \
    --cloud=gcp \
    --cloud-region=us-west \
    --cloud-type=m \
    --cloud-metadata="mykey=myval" \
    --cloud-gpu=nogpu \
    --repo=xxx \
    --driver=github \
    --cloud-hdd-size=10
```
Terraform template:
```hcl
terraform {
  required_providers {
    iterative = {
      source = "iterative/iterative"
    }
  }
}

provider "iterative" {}


resource "iterative_cml_runner" "runner" {
  repo = "xxx"
  token = "xxx"
  driver = "github"
  labels = "cml"
  idle_timeout = 1800
  name = "cml-40elk3xchx"
  single = "true"
  cloud = "gcp"
  region = "us-west"
  instance_type = "m"
  
  instance_hdd_size = 10
  
  
  spot_price = -1
  
  
  metadata = {
    mykey = "myval"
  }
}
```

Test:
```bash
./bin/cml.js runner \
    --single \
    --log=debug \
    --idle-timeout=1800 \
    --token=xxx \
    --cloud=gcp \
    --cloud-region=us-west \
    --cloud-type=m \
    --cloud-metadata="mykey=myval" \
    --cloud-metadata="mykey2=myval2" \
    --cloud-metadata="mykey3=myval3" \
    --cloud-gpu=nogpu \
    --repo=xxx \
    --driver=github \
    --cloud-hdd-size=10
```
Terraform template:
```hcl
terraform {
  required_providers {
    iterative = {
      source = "iterative/iterative"
    }
  }
}

provider "iterative" {}


resource "iterative_cml_runner" "runner" {
  repo = "xxx"
  token = "xxx"
  driver = "github"
  labels = "cml"
  idle_timeout = 1800
  name = "cml-40elk3xchx"
  single = "true"
  cloud = "gcp"
  region = "us-west"
  instance_type = "m"
  
  instance_hdd_size = 10
  
  
  spot_price = -1
  
  
  metadata = {
    mykey = "myval"
    mykey2 = "myval2"
    mykey3 = "myval3"
  }
}
```

### CODE REVIEW

**Comment by DanielBarnes** [comment]
@0x2b3bfa0 or @DavidGOrtega are you able to add a contrib branch and change the PR target while it is still marked as a draft?

**Comment by DanielBarnes** [comment]
Updated based on: https://github.com/iterative/cml/issues/430#issuecomment-913098542

**Comment by 0x2b3bfa0** [comment]
> _are you able to add a contrib branch and change the PR target while it is still marked as a draft?_

Yes, we can. Would you like to merge it first to a `contrib` branch on our repository?

**Comment by 0x2b3bfa0** [comment]
@DanielBarnes, counter–attacking with some suggestions and tests on https://github.com/DanielBarnes/cml/pull/1. Feel free to review and merge that into your pull request.

**Comment by DanielBarnes** [comment]
> > _are you able to add a contrib branch and change the PR target while it is still marked as a draft?_
> 
> Yes, we can. Would you like to merge it first to a `contrib` branch on our repository?

I'm fine with 'owning' this patch should any changes be required but I'm still knocking off ~6yrs of nodejs rust and would prefer it lives on a branch here since upstream changes need to be published before it can really be tested.

**Review by 0x2b3bfa0 — APPROVED** [review]
Awesome!

**Comment by 0x2b3bfa0** [comment]
Merged into a separate branch. We'll release it after the Terraform provider.

**Pull request merged**
