### PR TITLE
Update `yargs-parser`

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
Closes https://github.com/iterative/cml/issues/852 🎉

### CODE REVIEW

**Review by dacbd — CHANGES_REQUESTED** [review]
Im assuming this is supposed to allow: `--cloud-ssh-private="$(cat ./key.pem)"` instead of `--cloud-ssh-private="$(cat ./key.pem) "` which doesnt appear to be the case.

**Comment by 0x2b3bfa0** [comment]
@dacbd, sounds like [a stray space character](https://github.com/iterative/cml-playground/actions/runs/2890590522/workflow#L79) in your test workflow:

```diff
- --labels=private-key-852 -test 
+ --labels=private-key-852-test 
```

**Comment by dacbd** [comment]
indeed

**Review by dacbd — APPROVED** [review]
test fixed, and passes

**Pull request merged**
