### PR TITLE
improper terraform ref causes `Extraneous JSON` error

### PR DESCRIPTION
**Pull request by dacbd**
The correct terraform field is `aws_subnet_id` but it was being passed as `aws_subnet`

### CODE REVIEW

**Comment by 0x2b3bfa0** [comment]
Was the `tfObj` assignment necessary? 😅

**Comment by dacbd** [comment]
> Was the `tfObj` assignment necessary? 😅

makes hacking and future debugging easier.

**Comment by 0x2b3bfa0** [comment]
I'd prefer proper unit testing over `sed` hacking, and confess being allergic to unnecessary variables. 🤧 Still, no hard opinions on this.

**Comment by dacbd** [comment]
@0x2b3bfa0 do you have strong feelings about [`DEBUG`](https://github.com/winstonjs/winston#logging-levels) level logging it, IMO this is important information that I often go to for diagnosing issues that it is overly annoying to get at otherwise...

**Comment by 0x2b3bfa0** [comment]
@dacbd, if it's any better than a mere `cat ~/.cml/*/main.tf.json` after the command, sounds fine to me.

**Comment by dacbd** [comment]
> cat ~/.cml/*/main.tf.json

considering you have to nullglob and possibly get a large number of results or annoying extract the `cml-*` id out of the output yes I would prefer a zero effort guaranteed print of the information that I want ⏯️

**Review by 0x2b3bfa0 — APPROVED** [review]

**Pull request merged**
