### PR TITLE
testing refactor

### PR DESCRIPTION
**Pull request by myoung34**

### CODE REVIEW

**Comment by dacbd** [comment]
seems sus 🤔 ⛔ 🥇

**Comment by myoung34** [comment]
testing things. Youre solid (and wow, fast!)

If youre curious theres contact info on my page

**Comment by dacbd** [comment]
> testing things. Youre solid (and wow, fast!)
> 
> If youre curious theres contact info on my page

@myoung34 thanks, I'll take a look! if you find anything feel free to reach out, dabarnes@iterative.ai

**Comment by 0x2b3bfa0** [comment]
@myoung34, gold medal for making me wake up at 4:27 a.m. 🏅😉

**Comment by dacbd** [comment]
I did not wake up at 4am 😉. @myoung34 I will say the GitHub UI makes what happened look a bit misleading, are you testing opensource projects, random stuff, or a github search for actions: `self-hosted` + `run: |`

**Comment by myoung34** [comment]
Fuck, I owe you a beer @0x2b3bfa0

Email me at my contact and ill apologize in full.

**Comment by dacbd** [comment]
lol, didnt expect a poke back 😂

**Comment by 0x2b3bfa0** [comment]
No worries! Still, take the message for granted. 😄

**Comment by myoung34** [comment]
Well: good morning and one day ill publish what im doing and youll know. But in the meantime grab a coffee and know:

a) youre good
b) its all in whitehat nature
c) its interesting

**Comment by dacbd** [comment]
@myoung34 we'll keep an eye out for that link ⏳

**Comment by myoung34** [comment]
well shit.

**Comment by dacbd** [comment]
A bloopers section for when you publish findings 🙃

**Comment by myoung34** [comment]
Deal

**Comment by dacbd** [comment]
@myoung34 my final comment, we do have plans to publish our own write-up on our method of protecting self-hosted Github actions for open source repos, I'll make a note for us to cc you.

**Comment by myoung34** [comment]
Would you not, if only so i can preface (and maybe coordinate) with why its important to until that happens?

**Comment by dacbd** [comment]
@myoung34 for sure, reach out to me, and we can probably easily coordinate something. (I think you have plenty of time, the mentioned write-up isn't a high priority at the moment). While I believe many of our users don't have their repos public, the `cml (runner)` creates self-hosted runners so the content/research you are doing is very much relevant.

**Comment by kenji-miyake** [comment]
Hello. FYI, I posted a discussion thread about this. (Similar PRs are sent to my project as well.)
https://github.com/community/community/discussions/29757

If you know anything about it, I would appreciate your comments. :bow:

**Comment by myoung34** [comment]
@kenji-miyake @dacbd @0x2b3bfa0 https://marcyoung.us/post/zuckerpunch/

**Comment by 0x2b3bfa0** [comment]
Thank you very much! Nice “testing refactor” 😋

**Comment by casperdcl** [comment]
https://marcyoung.us/post/zuckerpunch I presume?

**Comment by casperdcl** [comment]
https://github.blog/changelog/2022-10-12-reverted-recent-change-that-caused-some-pull-requests-to-be-incorrectly-marked-as-merged/ for posterity :)

**Comment by 0x2b3bfa0** [comment]
@myoung34, would you like to cross link [our post](https://iterative.ai/blog/testing-external-contributions-using-github-actions-secrets) and [yours](https://marcyoung.us/post/zuckerpunch/)?

**Comment by 0x2b3bfa0** [comment]
Done

**Pull request merged**
