### PR TITLE
fix driver detection

### LINKED ISSUE #1066: Error: driver not set when trying to launch a runner for a Github Enterprise Repo
This error is raised when trying to launch a runner on a repo hosted on a private Github server. Is CML compatible with Github Enterprise ? Is this a problem with my configuration ?

Here are the logs of the error : 
error: Error: driver not set
    at getDriver (/home/user/.nvm/versions/node/v16.15.1/lib/node_modules/@dvcorg/cml/src/cml.js:64:22)
    at CML.runnerToken (/home/user/.nvm/versions/node/v16.15.1/lib/node_modules/@dvcorg/cml/src/cml.js:257:18)
    at CML.repoTokenCheck (/home/user/.nvm/versions/node/v16.15.1/lib/node_modules/@dvcorg/cml/src/cml.js:381:18)
    at run (/home/user/.nvm/versions/node/v16.15.1/lib/node_modules/@dvcorg/cml/bin/cml/runner.js:357:13)
    at Object.exports.handler (/home/user/.nvm/versions/node/v16.15.1/lib/node_modules/@dvcorg/cml/bin/cml/runner.js:427:11)
    at /home/user/.nvm/versions/node/v16.15.1/lib/node_modules/@dvcorg/cml/node_modules/yargs/build/index.cjs:1:8891
    at j (/home/user/.nvm/versions/node/v16.15.1/lib/node_modules/@dvcorg/cml/node_modules/yargs/build/index.cjs:1:4956)
    at M.handleValidationAndGetResult (/home/user/.nvm/versions/node/v16.15.1/lib/node_modules/@dvcorg/cml/node_modules/yargs/build/index.cjs:1:8860)
    at M.applyMiddlewareAndGetResult (/home/user/.nvm/versions/node/v16.15.1/lib/node_modules/@dvcorg/cml/node_modules/yargs/build/index.cjs:1:9502)
    at M.runCommand (/home/user/.nvm/versions/node/v16.15.1/lib/node_modules/@dvcorg/cml/node_modules/yargs/build/index.cjs:1:7231)
    at Xt.[runYargsParserAndExecuteCommands] (/home/user/.nvm/versions/node/v16.15.1/lib/node_modules/@dvcorg/cml/node_modules/yargs/build/index.cjs:1:57762)
    at Xt.parse (/home/user/.nvm/versions/node/v16.15.1/lib/node_modules/@dvcorg/cml/node_modules/yargs/build/index.cjs:1:39873)
    at Object.<anonymous> (/home/user/.nvm/versions/node/v16.15.1/lib/node_modules/@dvcorg/cml/bin/cml.js:90:4)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {"status":"terminated"}

I have the same error when trying with the official docker.

### PR DESCRIPTION
**Pull request by casperdcl**
- tried to fix - #1066

### CODE REVIEW

**Comment by 0x2b3bfa0** [comment]
I was about to open a pull request with the same change yesterday, but... are you sure it fixes the issue? 🤔

**Comment by 0x2b3bfa0** [comment]
As per the original bug report, this is the error:

https://github.com/iterative/cml/blob/4ec65178877f26f3227430b0daf36d854eb012a3/src/cml.js#L153

**Comment by 0x2b3bfa0** [comment]
### Class constructor

https://github.com/iterative/cml/blob/9cfa5aba464f6bfcf719489a7185cc621b8f7c90/src/cml.js#L117-L118

https://github.com/iterative/cml/blob/9cfa5aba464f6bfcf719489a7185cc621b8f7c90/src/cml.js#L128

### Driver detection function

https://github.com/iterative/cml/blob/4ec65178877f26f3227430b0daf36d854eb012a3/src/cml.js#L69-L80

### Thrown error

https://github.com/iterative/cml/blob/4ec65178877f26f3227430b0daf36d854eb012a3/src/cml.js#L151-L153

**Comment by 0x2b3bfa0** [comment]
I assume that the class constructor will always be called, and the only case where `this.driver` can remain unset is when none of the `inferDriver` conditions are met.

**Review by dacbd — DISMISSED** [review]
Perhaps a look at the things @0x2b3bfa0 mentioned is required, but these are clearly wrong, and we can fix them now.

**Comment by 0x2b3bfa0** [comment]
Yes, but #1209 (this) does **not** fix #1066 unless proven otherwise

**Comment by dacbd** [comment]
de-link #1066 and merge?

**Review by 0x2b3bfa0 — APPROVED** [review]
Fine, but doesn't fix #1066

**Review by 0x2b3bfa0 — APPROVED** [review]

**Pull request merged**
