### PR TITLE
Actions ci 

### PR DESCRIPTION
**Pull request by dacbd**
reduce action spam, don't request deployment while PRs are a "draft"

### CODE REVIEW

**Comment by dacbd** [comment]
I don't think the `if` condition is parsed before the `environment` expression

**Comment by casperdcl** [comment]
could add a pre-`authorize` step which `authorize` depends on?

**Comment by dacbd** [comment]
Could, it will probably bug me again soon and I'll try that out.

**Comment by casperdcl** [comment]
Mind you, not sure there's any point in not testing drafts. If you don't want to test some WIP, then leave it on a branch without opening a (draft) PR?

**Comment by dacbd** [comment]
> Mind you, not sure there's any point in not testing drafts. If you don't want to test some WIP, then leave it on a branch without opening a (draft) PR?

True:
https://github.com/iterative/terraform-provider-iterative/pull/325#issuecomment-988064273

**Pull request closed without merging**
