### PR TITLE
Replace deprecated `tar.gz` npm package

### LINKED ISSUE #405: npm install warning
During install, get this warning:

```
➜  ~ npm install -g @dvcorg/cml
npm WARN deprecated tar.gz@1.0.7: 
⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. 
Please use tar module instead: https://npmjs.com/tar
```

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
Closes #405

### CODE REVIEW

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 lgtm 🙏 
Please fix the conflicts and merge

**Review by DavidGOrtega — CHANGES_REQUESTED** [review]
Fix conflicts

**Comment by 0x2b3bfa0** [comment]
Tests are failing because the fix on #417. I'm going to cherry-pick that change.

**Pull request merged**
