### PR TITLE
Add deprecation notices to legacy commands

### LINKED ISSUE #1226: Legacy commands should print deprecation warnings

### PR DESCRIPTION
**Pull request by tasdomas**
Closes #1226

### CODE REVIEW

**Review by 0x2b3bfa0 — DISMISSED** [review]
`// Approved means that this pull request can be merged pressing the green button at the bottom of this page 👇🏼`

**Comment by tasdomas** [comment]
Updating for better usability in github.

**Comment by tasdomas** [comment]
example

**Review by 0x2b3bfa0 — APPROVED** [review]
❤️

**Pull request merged**
