### PR TITLE
Add exclusion list for environment variables

### LINKED ISSUE #721: cml-runner self-hosted issues
- `~/.cml/cml-*/` is not cleaned up
- `~/.cml/cml-*/` is not named according to `--name`
- feature request: local secrets (`cml runner --env` flag similar to `docker run --env`)

### PR DESCRIPTION
**Pull request by DavidGOrtega**
Excludes CML credentials passed as environment variables

 - Part of #721 
 - Needs https://github.com/iterative/terraform-provider-iterative/pull/665
 - Includes https://github.com/iterative/cml/pull/1164

### CODE REVIEW

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, I believe that `$PATH` is mandatory for runners to work. 🤔

**Comment by casperdcl** [comment]
The problem with whitelist-only is there are a few other things that a user would likely want preserved too...

- `NVIDIA_VISIBLE_DEVICES`
- `CUDA_VISIBLE_DEVICES`
- `LANG`

I'd prefer blacklisting CML config vars instead (`AWS_*ACCESS_KEY`)

(vis. https://github.com/iterative/cml/issues/721#issuecomment-960349575)

**Comment by dacbd** [comment]
Consider using `systemd-run` to start the `run.sh` ? Should scrub vars set in the session with export but maintain system controlled ones like `PATH`

**Comment by dacbd** [comment]
> Consider using `systemd-run` to start the `run.sh` ? Should scrub vars set in the session with export but maintain system controlled ones like `PATH`

Ehh don't think this plays nice when executed in a docker container, so probably not the best

**Comment by DavidGOrtega** [comment]
Im checking. It's happening something interesting.
I was counting with spawn( {shell:true}) which should create its own shell with system vars being expanded by the node ones. Funny is that in Macos seems to be fine... however inside a linux container Its not very happy...

**Comment by dacbd** [comment]
Confirm that this is really only an issue for cloud-based runners; pretty sure the fix will be in tpi?

**Comment by casperdcl** [comment]
I have this issue on on-prem as well as cloud...

**Comment by tasdomas** [comment]
This branch is now almost a year old. Should we make a decision on this?

**Comment by 0x2b3bfa0** [comment]
This issue does not have a clear solution because of a tremendous separation of concerns deficit between `cml` and `terraform-provider-iterative`

**Comment by 0x2b3bfa0** [comment]
@iterative/cml, proposing https://github.com/iterative/terraform-provider-iterative/pull/665 & https://github.com/iterative/cml/pull/1164 as a conservative and rather inelegant fix.

**Comment by 0x2b3bfa0** [comment]
> [_The problem with whitelist-only is there are a few other things that a user would likely want preserved too_](https://github.com/iterative/cml/pull/802#issuecomment-960913139)

Ideally, runners should get all the variables users get with a login session, but nothing else. 🤷🏼‍♂️

**Review by 0x2b3bfa0 — APPROVED** [review]

**Review by dacbd — CHANGES_REQUESTED** [review]
https://github.com/iterative/cml/pull/1164#issuecomment-1244635335 
 :warning: 
 
My test for this works so functionally g2g, but more discussion is required on whether this is what we want to do or what the communication plan is.

**Review by dacbd — CHANGES_REQUESTED** [review]
I will continue to request changes/block this until theses are resolved. https://github.com/iterative/cml/pull/802?notification_referrer_id=NT_kwDOABDfs7IyNjQwMzI3ODY3OjExMDU4NDM#pullrequestreview-1138260983

**Comment by 0x2b3bfa0** [comment]
As @casperdcl pointed out verbally, https://github.com/iterative/cml/pull/1164#issuecomment-1244635335 might not be a concern at all, because we don't explicitly encourage the use of implicit secrets (arguable) and they're available through secrets or Ci variables anyways.

**Comment by dacbd** [comment]
> As @casperdcl pointed out verbally, [#1164 (comment)](https://github.com/iterative/cml/pull/1164#issuecomment-1244635335) might not be a concern at all, because we don't explicitly encourage the use of implicit secrets (arguable) and they're available through secrets or Ci variables anyways.

I would still like to see us communicate this change for a time before enacted, or have a prepared response that provides examples for the user.

**Comment by casperdcl** [comment]
> As @casperdcl pointed out verbally

Now [also literally](https://github.com/iterative/cml/pull/1164#issuecomment-1289731746)™ :)

**Comment by 0x2b3bfa0** [comment]
@dacbd, after https://github.com/iterative/cml.dev/pull/423 removing https://github.com/iterative/cml/pull/1164#issuecomment-1244635335, this should be safe to unblocked?

**Pull request merged**
