### PR TITLE
Bump version to v0.19.0

### PR DESCRIPTION
**Pull request by casperdcl**
Approve me 🤖

### CODE REVIEW

**Review by 0x2b3bfa0 — APPROVED** [review]
🤖

**Comment by casperdcl** [comment]
ack nvm, forgot about `v0.major.minor` not `v0.minor.patch`

**Comment by 0x2b3bfa0** [comment]
What's that `v0.major.minor` aberration? 🤔 We [are supposed to] follow semantic versioning, and bumping the minor version is fine when introducing new features.

**Comment by casperdcl** [comment]
afaik https://semver.org/ has specific exceptions for `0.y.z`, TL;DR treating it more like `0.major.minor`

**Pull request closed without merging**
