### PR TITLE
Startup script

### PR DESCRIPTION
**Pull request by DavidGOrtega**
Adds base64 startup script. This side was needed in order to fully support https://github.com/iterative/terraform-provider-iterative/issues/74

### CODE REVIEW

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, it looks like you forgot to update the inline snapshot.

**Comment by DavidGOrtega** [comment]
WIP. I have not finished it

**Comment by 0x2b3bfa0** [comment]
👌  Understood, sorry for the intempestive comment. Can you please mark pull requests like this as [drafts](https://github.blog/2019-02-14-introducing-draft-pull-requests/) to keep me from lurking around them? 😸

**Comment by DavidGOrtega** [comment]
Yeah, we have to discuss that. DVC team puts a wip - in the tittle, we can also use drafts (I used to do it) but definitely we don't have to review unless is a contrib if no one of us ask for it.

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, can you please retry the GitLab job?

**Comment by DavidGOrtega** [comment]
GL is still having issues

**Comment by DavidGOrtega** [comment]
Anyway I think that its not going to pass, we dont have SG creation permissions

**Review by 0x2b3bfa0 — APPROVED** [review]
The GitLab issue doesn't have anything to do with the modifications introduced in this pull request.
Moving these concerns to https://github.com/iterative/cml/issues/447...

**Review by 0x2b3bfa0 — CHANGES_REQUESTED** [review]
By the way, are we accidentally deleting the `package-lock.json` file?

**Review by 0x2b3bfa0 — APPROVED** [review]
Nevermind, it was because of the `pacakge-lock.json` version downgrade.

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, please run again the GitLab check; it should succeed.

**Comment by DavidGOrtega** [comment]
I did it a few seconds before

**Pull request merged**
