### PR TITLE
Pin Vega and related dependencies on Dockerfile

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
[Detected by users on Discord](https://discord.com/channels/485586884165107732/728693131557732403/888927489160806430)

* Closes iterative/setup-cml#40 for containers

### CODE REVIEW

**Comment by casperdcl** [comment]
wouldn't it be better to run some tests with the docker images after building but before pushing?

**Comment by 0x2b3bfa0** [comment]
> wouldn't it be better to run some tests with the docker images after building but before pushing?

Doesn't look precisely easy/trivial/maintainable/beautiful, but I definitely see the value of running the test suite on the built containers before pushing them.

**Comment by 0x2b3bfa0** [comment]
Definitely! If our package can test itself after being installed (turtles all the way down), it would be nice to have this kind of test.

**Comment by 0x2b3bfa0** [comment]
🔔  @iterative/cml, it would be nice to expedite the approval of this pull request.

**Comment by casperdcl** [comment]
- https://github.com/iterative/setup-cml/issues/40 was closed so what issue does this PR solve?
- why aren't these deps included in `package.json`?

**Comment by 0x2b3bfa0** [comment]
> _Installing unpinned vega-lite package breaks Node 12 support setup-cml#40 was closed so what issue does this PR solve?_

* iterative/setup-cml#40 was closed prematurely, before we even noticed that the very same issue affected both our `setup-cml` GitHub Action and all of our container images.

* #720 solve**s** the issue for container images, and https://github.com/iterative/setup-cml/pull/41 solve**d** the same issue for the GitHub Action.

I have linked both pull requests to the same issue because they cover exactly the same issue, and I can't link pull requests to cross–repository issues without a closing keyword.

> why aren't these deps included in package.json?

It looks like we're on the same page: https://github.com/iterative/setup-cml/issues/47#issuecomment-924859213

**Review by casperdcl — APPROVED** [review]

**Pull request merged**
