### PR TITLE
Update maintainer in Dockerfile

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
Before: dvcorg <support@cml.dev>
After: CML <support@cml.dev>

### CODE REVIEW

**Comment by DavidGOrtega** [comment]
Not sure about this change @0x2b3bfa0 take into account that dvcorg is the maintainer of CML and indeed our npm package is ```@dvcorg/cml``` 

The one who can answer this question is @dmpetrov

**Comment by 0x2b3bfa0** [comment]
Maybe we should keep it as-is until [this proposal](https://iterativeai.slack.com/archives/C01SR9Q12LB/p1623403783036100) get any traction. I opened this pull request mainly to get rid of the comment. 😄

**Review by casperdcl — APPROVED** [review]
afaik regardless of any future package/account name changes, this email has and will always make most sense

**Comment by DavidGOrtega** [comment]
> afaik regardless of any future package/account name changes, this email has and will always make most sense

But the email remains the same? Is that a British humour finesse? 😃

**Comment by casperdcl** [comment]
I mean this particular docker image is maintained by CML so support should be `@cml.dev`, even though the org user may be different.

**Pull request merged**
