### PR TITLE
fix local --global install

### LINKED ISSUE #843: Cannot find module 'pseudoexec'
Tests are not passing. When executing

```
npm install -g
```

we have `Cannot find module 'pseudoexec'`

### PR DESCRIPTION
**Pull request by casperdcl**
- fixes #843

### CODE REVIEW

**Review by 0x2b3bfa0 — APPROVED** [review]
Saw this in StackOverflow half an hour ago, but didn't believe it was “the” solution. If this is the only way, it works for me.

**Comment by casperdcl** [comment]
Won't be able to tell if fixed until after it's merged :/

**Comment by 0x2b3bfa0** [comment]
🔮 It works 🐡

**Comment by 0x2b3bfa0** [comment]
Merging red because it's going to fail until merged. We use `pull_request_target` everywhere.

**Pull request merged**
