### PR TITLE
Housekeep/Removes sshPublicFromPrivateRsa

### PR DESCRIPTION
**Pull request by DavidGOrtega**
Removes an unused method.
It's mostly to avoid also package updates

### CODE REVIEW

**Review by 0x2b3bfa0 — APPROVED** [review]
:shipit: 🎉 If I recall correctly, there is a bit more of dead code for establishing SSH connections. Maybe it's worth another pull request one of these days. 🤔  Can we add some kind of dead code detector?

**Comment by 0x2b3bfa0** [comment]
> _The ssh connection is now used in runner tests_

Oh! I haven't read #689 in a while. 🤦🏼‍♂️

**Comment by DavidGOrtega** [comment]
> > _The ssh connection is now used in runner tests_
> 
> Oh! I haven't read #689 in a while. 🤦🏼‍♂️

And indeed it has changed a lot during this push. Now is simpler. Not yet still perfect however.
I'm going to document the downsides

**Comment by DavidGOrtega** [comment]
> > _The ssh connection is now used in runner tests_
> 
> Oh! I haven't read #689 in a while. 🤦🏼‍♂️

And indeed it has changed a lot during this push. Now is simpler. Not yet still perfect however.
I'm going to document the downsides

**Pull request merged**
