### PR TITLE
ci: expose --user-email --user-name

### LINKED ISSUE #942: Feature Request: Add `--user-email` and `--user-name` options to `cml ci`
I know with `cml pr` it's possible to add `--user-email` and `--user-name`, but is it possible to do this with `cml ci` so that new commits can come from an account that we specify rather than https://github.com/iterative-olivaw

### PR DESCRIPTION
**Pull request by casperdcl**
- add `--user-name`, `--user-email`
- update `--help` wording
- fixes #942

### CODE REVIEW

**Review by 0x2b3bfa0 — APPROVED** [review]
🚀

**Comment by casperdcl** [comment]
Should we also open a follow-up for [convenience options](https://github.com/iterative/cml/issues/942#issuecomment-1094758032)?

**Comment by 0x2b3bfa0** [comment]
Sounds like a <kbd>p1.618–interesting</kbd> improvement

**Review by DavidGOrtega — CHANGES_REQUESTED** [review]
I have a question.
Does this PR allows to modify the cml email and user?
I do not see how 😅

**Comment by DavidGOrtega** [comment]
Fix tests 🙏

**Review by DavidGOrtega — APPROVED** [review]

**Pull request merged**
