### PR TITLE
test dispatch & basic OS commands

### PR DESCRIPTION
**Pull request by casperdcl**
we don't test on pushes so this'll be useful to test e.g. #733

### CODE REVIEW

**Comment by 0x2b3bfa0** [comment]
In the case of #733, it wouldn't matter if we test on `push` or just on `pull_request` (synchronization)... we can manually `workflow_dispatch` any branch from the dropdown as you have in mind, or simply update the pull request like in https://github.com/iterative/cml/pull/732/commits/6b8403c35529a2f19cb8733ae8ef52bb95fcbe25 and let the tests run again.

**Review by 0x2b3bfa0 — APPROVED** [review]
If you feel it necessary after https://github.com/iterative/cml/pull/734#issuecomment-924883799, :shipit:

**Comment by casperdcl** [comment]
unfortunately still passes. Needs to actually install & run some commands...

**Comment by casperdcl** [comment]
wonder if `--version` will be good enough. Trying to avoid having to do `cml publish --md` :)

**Comment by casperdcl** [comment]
-.- rate limiting

**Pull request merged**
