### PR TITLE
Add the --single option to the Terraform template

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
This pull request passes the newly introduced `--single` option to the launched cloud runners.

Closes iterative/terraform-provider-iterative#94, requires https://github.com/iterative/terraform-provider-iterative/pull/103

### CODE REVIEW

**Comment by 0x2b3bfa0** [comment]
Untested on the cloud, but templates look promising.

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 not sure, probably an integration test with idle-timeout 0 not timing out would suffice?

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 are you adding the test or are. we merging straignt?

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, unless you prefer otherwise, I'd vote for merging. Template tests seem enough for this particular case, at least for checking that the option gets passed to Terrafrom.

**Review by DavidGOrtega — APPROVED** [review]
lgtm 🚀

**Pull request merged**
