### PR TITLE
Bump CUDA to 11.2.1 on container images

### LINKED ISSUE #766: upgrade cuda version to support tf 2.6.0
Hi, We were unable to use tf 2.6.0 with the  `dvc2-base1-gpu` docker image. The problem is probably due to the image using cuda version [11.0.3](https://github.com/iterative/cml/blob/9909e2a809af0467f5b2f3cb0f08ff51c07d0cbb/.github/workflows/test-deploy.yml#L108) which is not compatible with tf 2.6.0 (requires [11.2](https://www.tensorflow.org/install/source#gpu)). Are there plans to upgrade the cuda version?

Original [question on discord](https://discord.com/channels/485586884165107732/728693131557732403/892392555336065065) for context.

Many thanks.

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
They follow semantic versioning, right? 🤔  Closes #766; I haven't performed any kind of [manual] regression test yet.

### CODE REVIEW

**Comment by casperdcl** [comment]
uh, not really. Often `pytorch` and `tensorflow` will break with a "minor" or even "patch" CUDA bump. There's a reason `@torvalds` hates NVIDIA :)

**Review by casperdcl — APPROVED** [review]
we can always revert if something breaks :innocent:

**Comment by 0x2b3bfa0** [comment]
Bitbucket tests are broken. 😞

**Comment by 0x2b3bfa0** [comment]
d107178c10a908b3ec8aae3082f6dd58

**Pull request merged**
