### PR TITLE
send-comment rev-parse

### LINKED ISSUE #788: Error when combining `cml pr` and `cml send-comment --pr`
I'm getting the following error:

```json
{
    "level":"error",
    "message":"Cannot destructure property 'url' of 'commitPr' as it is undefined.",
    "stack":"TypeError: Cannot destructure property 'url' of 'commitPr' as it is undefined.\n    at CML.commentCreate (/usr/lib/node_modules/@dvcorg/cml/src/cml.js:126:15)\n    at async Object.exports.handler (/usr/lib/node_modules/@dvcorg/cml/bin/cml/send-comment.js:13:15)"
}
```

When combining `cml pr` and `cml send-comment --pr` in the same workflow. 

Here is a minimal example to reproduce:

https://github.com/iterative/test-cml-send-comment-pr

And the failing workflow:

https://github.com/iterative/test-cml-send-comment-pr/runs/4038830121?check_suite_focus=true

### LINKED ISSUE #807: `cml send-comment` fails in BB without existing PRs
```sh
{"level":"error","message":"invalid json response body at https://api.bitbucket.org/2.0/repositories/DavidOrtega%2Ffashion-mnist/commit/046780cb574ff969bcf48888b16044ba15141dce/pullrequests?state=OPEN reason: Unexpected end of JSON input","stack":"FetchError: invalid json response body at https://api.bitbucket.org/2.0/repositories/DavidOrtega%2Ffashion-mnist/commit/046780cb574ff969bcf48888b16044ba15141dce/pullrequests?state=OPEN reason: Unexpected end of JSON input\n    at /usr/lib/node_modules/@dvcorg/cml/node_modules/node-fetch/lib/index.js:273:32\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async BitbucketCloud.request (/usr/lib/node_modules/@dvcorg/cml/src/drivers/bitbucket_cloud.js:245:11)\n    at async BitbucketCloud.paginatedRequest (/usr/lib/node_modules/@dvcorg/cml/src/drivers/bitbucket_cloud.js:258:30)\n    at async BitbucketCloud.commitPrs (/usr/lib/node_modules/@dvcorg/cml/src/drivers/bitbucket_cloud.js:71:19)\n    at async CML.commentCreate (/usr/lib/node_modules/@dvcorg/cml/src/cml.js:132:31)\n    at async Object.exports.handler (/usr/lib/node_modules/@dvcorg/cml/bin/cml/send-comment.js:13:15)","type":"invalid-json"}
```

### PR DESCRIPTION
**Pull request by DavidGOrtega**
Surprisingly it looks like we lost the ability to parse refs long time ago!?  (Everybody remembers it but send-comment predating `--pr` has the same issue).
Also fixes some BB issues

- Adds rev parse closes #788 
- closes #807

### CODE REVIEW

**Comment by DavidGOrtega** [comment]
image

image

image

**Review by casperdcl — COMMENTED** [review]
maybe should add some tests for this?

**Comment by DavidGOrtega** [comment]
> maybe should add some tests?

Im doing integration tests in fashion_mnist.
All it tests are going to run against every single release.

I can add some also in our dummy repos but I would like to deprecate them in favour of a real thing

**Review by casperdcl — APPROVED** [review]
lgtm. let me know if you're ready for merge

**Comment by DavidGOrtega** [comment]
Ready to be merged unless you want me to create the PR in dummy repos to test it

**Comment by 0x2b3bfa0** [comment]
Related to https://github.com/iterative/cml/issues/880

**Pull request merged**
